/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import Models.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import Dijkastra.*;
/**
 *
 * @author thenullterminator
 */

class InvalidInput extends Exception{ //Defining exception.
    
    InvalidInput(String s){
        super(s);
    }
}


public class LessInteractive extends javax.swing.JFrame {
    
    Graph g=new Graph();//Creating New Graph.
    /**
     * Creates new form LessInteractive
     */
    
    public LessInteractive() {
        initComponents();
    }
    
    public static Boolean isNumber(String s){
        
        try{
            int d=Integer.parseInt(s);
        }
        catch(NumberFormatException e){
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addVertexName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addVertexX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addVertexY = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editVertexName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        editVertexX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editVertexY = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchVertexName = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        deleteVertexName = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addEdgeFrom = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        addEdgeTo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        addEdgeWeight = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        editEdgeFrom = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        editEdgeTo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        editEdgeWeight = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        searchEdgeTo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        searchEdgeFrom = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        deleteEdgeFrom = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        deleteEdgeTo = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        loadFile = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        exportFile = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortestPath = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        shortestDist = new javax.swing.JTextArea();

        jLabel5.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel5.setText("Add Vertex");

        jLabel6.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel6.setText("Name");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel7.setText("X Cord ");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel8.setText("Y Cord");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizing Dijkstra's Algorithm");
        setBackground(java.awt.Color.gray);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel1.setText("Add Vertex");

        jLabel2.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        addVertexName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVertexNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel3.setText("X Cord ");

        addVertexX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVertexXActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel4.setText("Y Cord");

        addVertexY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVertexYActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel9.setText("Edit Vertex");

        jLabel10.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel10.setText("Name");

        editVertexName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVertexNameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel11.setText("X Cord ");

        editVertexX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVertexXActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel12.setText("Y Cord");

        editVertexY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVertexYActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel13.setText("Search Vertex");

        jLabel14.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel14.setText("Name");

        searchVertexName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVertexNameActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel36.setText("Delete Vertex");

        jLabel37.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel37.setText("Name");

        deleteVertexName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVertexNameActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel11)
                                .addGap(3, 3, 3)
                                .addComponent(editVertexX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editVertexY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(editVertexX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(editVertexY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(searchVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(36, 36, 36)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(deleteVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jButton4)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(addVertexX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addVertexY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addVertexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(addVertexX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addVertexY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vertex", jPanel1);

        jLabel17.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel17.setText("Add Edge");

        jLabel18.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel18.setText("From");

        addEdgeFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeFromActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel19.setText("To");

        addEdgeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeToActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel20.setText("Weight");

        addEdgeWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeWeightActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel21.setText("Edit Edge");

        jLabel22.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel22.setText("From");

        editEdgeFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEdgeFromActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel23.setText("To");

        editEdgeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEdgeToActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel24.setText("Weight");

        editEdgeWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEdgeWeightActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        searchEdgeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEdgeToActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel30.setText("To");

        searchEdgeFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEdgeFromActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel31.setText("From");

        jLabel32.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel32.setText("Search Edge");

        jButton10.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel33.setText("Delete Edge");

        jLabel34.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel34.setText("From");

        deleteEdgeFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEdgeFromActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel35.setText("To");

        deleteEdgeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEdgeToActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel23)
                                .addGap(3, 3, 3)
                                .addComponent(editEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel35)
                                .addGap(3, 3, 3)
                                .addComponent(deleteEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel30)
                                .addGap(3, 3, 3)
                                .addComponent(searchEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editEdgeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(editEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(editEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(editEdgeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addGap(35, 35, 35)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(searchEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(searchEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton10)
                .addGap(28, 28, 28)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(deleteEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(deleteEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton11)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel19)
                        .addGap(3, 3, 3)
                        .addComponent(addEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEdgeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(addEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(addEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(addEdgeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Edge", jPanel4);

        jLabel15.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel15.setText("Add an existing graph from a text file");

        jLabel16.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel16.setText("File Path");

        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jButton5.setText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel15)
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(loadFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Load Graph", jPanel8);

        jLabel25.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel25.setText("Export Graph");

        jLabel26.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel26.setText("Destination");

        jLabel27.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel27.setText("Source");

        exportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportFileActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton7.setText("Shortest Path");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel28.setText("Dijkstra's Algorithm");

        jLabel38.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jLabel38.setText("File Path");

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Purisa", 1, 14)); // NOI18N
        jButton9.setText("Export");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        shortestPath.setBackground(java.awt.Color.white);
        shortestPath.setColumns(20);
        shortestPath.setRows(5);
        shortestPath.setText("Shortest Path");
        jScrollPane1.setViewportView(shortestPath);

        shortestDist.setBackground(java.awt.Color.white);
        shortestDist.setColumns(20);
        shortestDist.setRows(5);
        shortestDist.setText("Shortest Distance");
        shortestDist.setAutoscrolls(false);
        jScrollPane2.setViewportView(shortestDist);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(exportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel28))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel25))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel28)
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dijkstra", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVertexYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVertexYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVertexYActionPerformed

    private void addVertexXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVertexXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVertexXActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(addVertexName.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(addVertexX.getText().trim().isEmpty() || addVertexY.getText().trim().isEmpty()){
                throw new InvalidInput("Coordinates cannot be blank");
            }
            if( !isNumber(addVertexX.getText().trim()) || !isNumber(addVertexY.getText().trim()) ){
                throw new InvalidInput("Coordinates should be Numeric");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String name=addVertexName.getText().trim();
            int X=Integer.parseInt(addVertexX.getText().trim());
            int Y=Integer.parseInt(addVertexY.getText().trim());
//            System.out.println(name);
            Node n=new Node();
            n.setName(name);
            n.setX(X);
            n.setY(Y);
            
            if(g.searchNode(n.getName())!=null){
                JOptionPane.showMessageDialog(null,"Vertex Name is already used");
                return ;
            }
            
            g.addNode(n); //Adding Node to node list.
            
            addVertexName.setText("");
            addVertexX.setText("");
            addVertexY.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addVertexNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVertexNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVertexNameActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editVertexNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVertexNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editVertexNameActionPerformed

    private void editVertexXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVertexXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editVertexXActionPerformed

    private void editVertexYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVertexYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editVertexYActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(searchVertexName.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String name=searchVertexName.getText().trim();
            
//            System.out.println(name);
            
            Node n2=g.searchNode(name);
            
            if(n2==null){
                JOptionPane.showMessageDialog(null,"Vertex not present");
                return ;
            }
            else{
                JOptionPane.showMessageDialog(null,"Name: "+n2.getName()+" X: "+n2.getX()+" Y: "+n2.getY());
            }
            searchVertexName.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchVertexNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVertexNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchVertexNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(editVertexName.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(editVertexX.getText().trim().isEmpty() || editVertexY.getText().trim().isEmpty()){
                throw new InvalidInput("Coordinates cannot be blank");
            }
            if( !isNumber(editVertexX.getText().trim()) || !isNumber(editVertexY.getText().trim()) ){
                throw new InvalidInput("Coordinates should be Numeric");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String name=editVertexName.getText().trim();
            int X=Integer.parseInt(editVertexX.getText().trim());
            int Y=Integer.parseInt(editVertexY.getText().trim());
//            System.out.println(name);
            Node n=new Node();
            n.setName(name);
            n.setX(X);
            n.setY(Y);
            
            Node n2=g.searchNode(n.getName());
            if(n2==null){
                JOptionPane.showMessageDialog(null,"Vertex not present");
                return ;
            }
            
            g.removeNode(n2);
            g.addNode(n); //Adding New Node to node list.
            
            editVertexName.setText("");
            editVertexX.setText("");
            editVertexY.setText("");
//            g.printNodes();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addEdgeFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeFromActionPerformed

    private void addEdgeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeToActionPerformed

    private void addEdgeWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeWeightActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(addEdgeFrom.getText().trim().isEmpty() || addEdgeTo.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(addEdgeFrom.getText().trim().equals(addEdgeTo.getText().trim())){
                throw new InvalidInput("From and To vertex cannot be same");
            }
            if(addEdgeWeight.getText().trim().isEmpty()){
                throw new InvalidInput("Weight cannot be blank");
            }
            if( !isNumber(addEdgeWeight.getText().trim())){
                throw new InvalidInput("Weight should be Numeric");
            }
            if(Integer.parseInt(addEdgeWeight.getText().trim())<0){
                throw new InvalidInput("Weight should be Non Negative");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String from=addEdgeFrom.getText().trim();
            String to=addEdgeTo.getText().trim();
            int weight=Integer.parseInt(addEdgeWeight.getText().trim());
            
            if(g.searchNode(from)==null){
                JOptionPane.showMessageDialog(null,"From Vertex Does Not Exist");
                return ;
            }
            
            if(g.searchNode(to)==null){
                JOptionPane.showMessageDialog(null,"To Vertex Does Not Exist");
                return ;
            }
            
           
//            System.out.println(name);
            Edge e=new Edge();
            e.setFrom(from);
            e.setTo(to);
            e.setWeight(weight);
            
            if(g.searchEdge(from, to)!=null){
                JOptionPane.showMessageDialog(null,"Edge is already present");
                return ;
            }
            
            
            g.addEdge(e);//Adding edge to the edge list.
            
            addEdgeFrom.setText("");
            addEdgeTo.setText("");
            addEdgeWeight.setText("");
//            System.out.println("___________________________");
//            g.printEdges();
//            System.out.println("___________________________");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void editEdgeFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEdgeFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEdgeFromActionPerformed

    private void editEdgeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEdgeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEdgeToActionPerformed

    private void editEdgeWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEdgeWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEdgeWeightActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(editEdgeFrom.getText().trim().isEmpty() || editEdgeTo.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(editEdgeFrom.getText().trim().equals(editEdgeTo.getText().trim())){
                throw new InvalidInput("From and To vertex cannot be same");
            }
            if(editEdgeWeight.getText().trim().isEmpty()){
                throw new InvalidInput("Weight cannot be blank");
            }
            if( !isNumber(editEdgeWeight.getText().trim())){
                throw new InvalidInput("Weight should be Numeric");
            }
             if(Integer.parseInt(editEdgeWeight.getText().trim())<0){
                throw new InvalidInput("Weight should be Non Negative");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String from=editEdgeFrom.getText().trim();
            String to=editEdgeTo.getText().trim();
            int weight=Integer.parseInt(editEdgeWeight.getText().trim());
            
            if(g.searchNode(from)==null){
                JOptionPane.showMessageDialog(null,"From Vertex Does Not Exist");
                return ;
            }
            
            if(g.searchNode(to)==null){
                JOptionPane.showMessageDialog(null,"To Vertex Does Not Exist");
                return ;
            }
           
//            System.out.println(name);
            Edge e=g.searchEdge(from, to);
            
            if(e==null){
                JOptionPane.showMessageDialog(null,"Edge is Not present");
                return ;
            }
            g.changeWeight(e, weight);
//            e=g.searchEdge(to, from);
//            g.changeWeight(e, weight);
            
            editEdgeFrom.setText("");
            editEdgeTo.setText("");
            editEdgeWeight.setText("");
//            System.out.println("___________________________");
//            g.printEdges();
//            System.out.println("___________________________");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void searchEdgeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEdgeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEdgeToActionPerformed

    private void searchEdgeFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEdgeFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEdgeFromActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(searchEdgeFrom.getText().trim().isEmpty() || searchEdgeTo.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(searchEdgeFrom.getText().trim().equals(searchEdgeTo.getText().trim())){
                throw new InvalidInput("From and To vertex cannot be same");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String from=searchEdgeFrom.getText().trim();
            String to=searchEdgeTo.getText().trim();
            
            
            if(g.searchNode(from)==null){
                JOptionPane.showMessageDialog(null,"From Vertex Does Not Exist");
                return ;
            }
            
            if(g.searchNode(to)==null){
                JOptionPane.showMessageDialog(null,"To Vertex Does Not Exist");
                return ;
            }
           
            Edge e=g.searchEdge(from, to);
            if(e==null){
                JOptionPane.showMessageDialog(null,"Edge is Not present");
                return ;
            }
            else{
                JOptionPane.showMessageDialog(null,"From: "+e.getFrom()+" To: "+e.getTo()+" Weight: "+e.getWeight());
            }
            searchEdgeFrom.setText("");
            searchEdgeTo.setText("");
//            System.out.println("___________________________");
//            g.printEdges();
//            System.out.println("___________________________");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void deleteEdgeFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEdgeFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEdgeFromActionPerformed

    private void deleteEdgeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEdgeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEdgeToActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
       Boolean flag=false;
        try{
            if(deleteEdgeFrom.getText().trim().isEmpty() || deleteEdgeTo.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(deleteEdgeFrom.getText().trim().equals(deleteEdgeTo.getText().trim())){
                throw new InvalidInput("From and To vertex cannot be same");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String from=deleteEdgeFrom.getText().trim();
            String to=deleteEdgeTo.getText().trim();
            
            
            if(g.searchNode(from)==null){
                JOptionPane.showMessageDialog(null,"From Vertex Does Not Exist");
                return ;
            }
            
            if(g.searchNode(to)==null){
                JOptionPane.showMessageDialog(null,"To Vertex Does Not Exist");
                return ;
            }
            Edge e=g.searchEdge(from, to);
            g.removeEdge(e);
//            e=g.searchEdge(to, from);
//            g.removeEdge(e);
            deleteEdgeFrom.setText("");
            deleteEdgeTo.setText("");
//            System.out.println("___________________________");
//            g.printEdges();
//            System.out.println("___________________________");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void deleteVertexNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVertexNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteVertexNameActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
//        g.printNodes();
         Boolean flag=false;
        try{
            if(deleteVertexName.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String name=deleteVertexName.getText().trim();
            
            System.out.println(name);
            
            Node n2=g.searchNode(name);
            g.removeNode(n2);
            g.removeAllEdges(n2);
            deleteVertexName.setText("");
//            g.printNodes();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileActionPerformed

    private void exportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportFileActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        Boolean flag=false;
        try{
            if(jTextField26.getText().trim().isEmpty() || jTextField18.getText().trim().isEmpty()){
                throw new InvalidInput("Vertex Name cannot be blank");
            }
            if(jTextField26.getText().trim().equals(jTextField18.getText().trim())){
                throw new InvalidInput("Source and Destination vertex cannot be same");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String src=jTextField26.getText().trim();
            String dest=jTextField18.getText().trim();
           
            if(g.searchNode(src)==null){
                JOptionPane.showMessageDialog(null,"Source Vertex Does Not Exist");
                return ;
            }
            
            if(g.searchNode(dest)==null){
                JOptionPane.showMessageDialog(null,"Destination Vertex Does Not Exist");
                return ;
            }
            TreeMap<String,ArrayList<Edge>> gr=g.createAdjList();
            System.out.println(gr.size());
            Algo x=new Algo(g.createAdjList(),src,dest);
            x.implement();
            String path=x.getPath();
            int dist=x.getDistance();
            
            if(dist!=Integer.MAX_VALUE){
                shortestDist.setText("Shortest Distance: "+dist);
            }
            
            shortestPath.setText("Shortest Path: \n"+path);
            jTextField26.setText("");
            jTextField18.setText("");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Boolean flag=false;
        try{
            if(exportFile.getText().trim().isEmpty()){
                throw new InvalidInput("File Name cannot be blank");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String fname=exportFile.getText().trim();
            
            try{
               
               FileWriter wr=new FileWriter(fname);
               
               ArrayList<Node> sn=g.sortedNodes();
               ArrayList<Edge> se=g.sortedEdges();
               
               wr.write(sn.size()+"\n");
               
               for(Node n:sn){
                   wr.append(n.getName()+" "+n.getX()+" "+n.getY()+"\n");
               }
               
               wr.append(se.size()+"\n");
               
               for(Edge e:se){
                   wr.append(e.getFrom()+" "+e.getTo()+" "+e.getWeight()+"\n");
               }
               
               wr.close();
            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
            exportFile.setText("");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Boolean flag=false;
        try{
            if(loadFile.getText().trim().isEmpty()){
                throw new InvalidInput("File Name cannot be blank");
            }
        }
        catch(InvalidInput e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            flag=true;
        }
        
        if(!flag){
            
            String fname=loadFile.getText().trim();
            
            try{
               
                File obj =new File(fname);
                Scanner sc=new Scanner(obj);
                int n=sc.nextInt();
                System.out.println(n+"f");
                sc.nextLine();//Clearing the buffer.
                for(int i=0;i<n;i++){
                    String x=sc.nextLine();
                    System.out.println(x);
                    String[] s=x.split(" ");
                    Node p=new Node();
                    p.setName(s[0]);
                    p.setX(Integer.parseInt(s[1]));
                    p.setY(Integer.parseInt(s[2]));
                    g.addNode(p);
//                    if(g.searchNode(s[0])==null)
//                    g.addNode(p);
//                    else 
//                    throw new Exception();
                }
                g.printNodes();
                
                int m=sc.nextInt();
                sc.nextLine();
                for(int i=0;i<m;i++){
                    String x=sc.nextLine();
                    String[] s=x.split(" ");
                    
                    Edge e=new Edge();
                    e.setFrom(s[0]);
                    e.setTo(s[1]);
                    e.setWeight(Integer.parseInt(s[2]));
                    g.addEdge(e);
                    
//                    if(g.searchEdge(s[0],s[1])==null)
//                    g.addEdge(e);
//                    else 
//                    throw new Exception();
                }
//                g.printEdges();
                if(sc.hasNextLine()) throw new Exception();
                sc.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,"Invalid Input ");
            }
            loadFile.setText("");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessInteractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessInteractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessInteractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessInteractive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessInteractive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addEdgeFrom;
    private javax.swing.JTextField addEdgeTo;
    private javax.swing.JTextField addEdgeWeight;
    private javax.swing.JTextField addVertexName;
    private javax.swing.JTextField addVertexX;
    private javax.swing.JTextField addVertexY;
    private javax.swing.JTextField deleteEdgeFrom;
    private javax.swing.JTextField deleteEdgeTo;
    private javax.swing.JTextField deleteVertexName;
    private javax.swing.JTextField editEdgeFrom;
    private javax.swing.JTextField editEdgeTo;
    private javax.swing.JTextField editEdgeWeight;
    private javax.swing.JTextField editVertexName;
    private javax.swing.JTextField editVertexX;
    private javax.swing.JTextField editVertexY;
    private javax.swing.JTextField exportFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField loadFile;
    private javax.swing.JTextField searchEdgeFrom;
    private javax.swing.JTextField searchEdgeTo;
    private javax.swing.JTextField searchVertexName;
    private javax.swing.JTextArea shortestDist;
    private javax.swing.JTextArea shortestPath;
    // End of variables declaration//GEN-END:variables
}
